name: DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo çek
        uses: actions/checkout@v4

      - name: Docker build
        run: docker build -t devops-app .

      - name: Container test çalıştır
        run: docker run devops-app
